#!/bin/sh
GIT_WORK_TREE=/Users/khantil/Developer/MCSStudy/DevOps/PipelineBasics/deploy/production-www/ git checkout -f
echo "Pushed to production"
cd /Users/khantil/Developer/MCSStudy/DevOps/PipelineBasics/deploy/production-www/
npm install
node main.js 9090
